### PR TITLE
Generate optional TypeScript fields when @include or @skip directive is used

### LINKED ISSUE #888: Codegen should take @include and @skip into account
If we use `@include` or `@skip` directives on a non-nullable field, the code generation output should be nullable because we can guarantee that the data won't always exist.

### PR DESCRIPTION
**Pull request by mwilliamson**
This makes generated TypeScript fields optional if the `@include` directive is used. Fixes #888.

### CODE REVIEW

**Comment by OzzieOrca** [comment]
Does this support `@skip` as well?

**Comment by mwilliamson** [comment]
> Does this support `@skip` as well?

Yes, `@skip` should also be supported. I've added a test case to cover this.

I've also the CLA.

**Comment by MargaretKrutikova** [comment]
Very much appreciated, @mwilliamson! Just stumbled upon this issue at work, would be great to have it merged 🙂

**Comment by hlehmann** [comment]
any news on this ?

**Comment by chaffeqa** [comment]
If it helps, we are using this PR (via https://www.npmjs.com/package/patch-package) and its working great!  Thx @mwilliamson

**Comment by dobesv** [comment]
I wonder if rebasing on latest master will clear up that build error.

**Comment by pelhage** [comment]
We ran into a bug caused by this issue. Would be nice to see this PR introduced!

**Comment by vidmantasa** [comment]
Any news on this?

**Comment by audriuss** [comment]
Please, merge the PR :) Please

**Comment by jaminhaber** [comment]
Can this be merged? It would come in very handy for me on a project

**Comment by samageloff** [comment]
Really looking forward to this!

**Pull request closed without merging**
