### PR TITLE
Possibility to force camel casing

### PR DESCRIPTION
**Pull request by tomitrescak**

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
@tomitrescak what are you wanting to accomplish here?

**Comment by tomitrescak** [comment]
Well, I would like to have class names as per recommendations. The package is awesome, but seeing class names with a weird snake case with lowercase letters breaks my convention heart. It’s just that I never seen classes such as My_snake_class. It would be great to have a parameter that decides this.

**Comment by trevor-scheer** [comment]
@tomitrescak sorry for the delay on follow up, I'm trying to triage PRs and issues as I'm able but we're quite busy here.

This is more of a feature request than an actual PR - would you mind opening an issue as such?
Else, a PR with a more complete implementation would also be entertained, but I'd prefer we have the chance to align on any decisions first. Thanks!

**Comment by tomitrescak** [comment]
Can be ingnored since the graphql-code-generator came to exist.

**Pull request closed without merging**
