### PR TITLE
fix: support `type: module` with `.cjs`file extension #2342

### LINKED ISSUE #2342: Extension cannot be used it type is set to module
**Intended outcome:**

The extensions should work and load the local schema.

**Actual outcome:**

Cannot load schema.

```
[ERROR] A config file failed to load with options: {"configPath":"/***/***/Desktop/test","requireConfig":true}.
    The error was: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /***/***/Desktop/test/apollo.config.js
require() of ES modules is not supported.
require() of /***/***/Desktop/test/apollo.config.js from /***/***/.vscode/extensions/apollographql.vscode-apollo-1.19.3/node_modules/import-fresh/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename apollo.config.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /***/***/Desktop/test/package.json.

    at Object.loadConfig (/***/***/.vscode/extensions/apollographql.vscode-apollo-1.19.3/node_modules/apollo-language-server/lib/config/loadConfig.js:42:34)
    at async GraphQLWorkspace.reloadProjectForConfig (/***/***/.vscode/extensions/apollographql.vscode-apollo-1.19.3/node_modules/apollo-language-server/lib/workspace.js:107:22)
    at /***/***/.vscode/extensions/apollographql.vscode-apollo-1.19.3/src/extension.ts:77:17
    at handleNotification (/***/***/.vscode/extensions/apollographql.vscode-apollo-1.19.3/node_modules/vscode-jsonrpc/lib/main.js:489:43)
    at processMessageQueue (/***/***/.vscode/extensions/apollographql.vscode-apollo-1.19.3/node_modules/vscode-jsonrpc/lib/main.js:260:17)
    at Immediate._onImmediate (/***/***/.vscode/extensions/apollographql.vscode-apollo-1.19.3/node_modules/vscode-jsonrpc/lib/main.js:247:13)

```

This is because in the `package.json` there is `"type": "module"` set. Node then treats files as modules and not commonjs. This means that `module.exports` does not work.

**How to reproduce the issue:**

1. Create a `package.json`. (See below)
2. Add a config file `apollo.config.js` with an endpoint (See below)
3. Reload window and reload schema

```json
{
  "private": true,
  "type": "module"
}
```

```javascript
module.exports = {
  client: {
    service: {
      name: 'foo',
      url: 'https://example.org/graphql',
    },
  },
}
```

**Versions**

v1.19.3

**Additional Information**

https://github.com/apollographql/apollo-tooling/blob/be117f3140247b71b792a6b52b2ed26f2f76da02/packages/apollo-language-server/src/config/loadConfig.ts#L21-L25

I'm not sure but a possible solution could be also accepting `apollo.config.cjs` as a supported config file option. Should be tested

### PR DESCRIPTION
**Pull request by alexanderniebuhr**
close #2342

TODO:

- [x] Update CHANGELOG.md\* with your change (include reference to issue & this PR)
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass

\*Make sure changelog entries note which project(s) has been affected. See older entries for examples on what this looks like.

### CODE REVIEW

**Comment by alexanderniebuhr** [comment]
Not sure why CI Tests fail. Local Tests are passing all

Screenshot 2021-07-12 at 21 40 30

**Comment by alexanderniebuhr** [comment]
@jgzuke just saw you answering PRs and doing heavy work on the transition branch.
If you move the apollo vs code extension, it would be great to get this included asap.

Let me know if you need any more information!

**Comment by alexanderniebuhr** [comment]
https://github.com/apollographql/vscode-graphql/pull/4

**Comment by abernix** [comment]
@alexanderniebuhr Thanks for moving that over to the new VS Code repository.  Since there are remaining bits in this repository (e.g., the `apollo` CLI) that also use this file ([it's a platform concern](https://www.apollographql.com/docs/devtools/apollo-config/)), should we re-open this and land this PR?

**Comment by abernix** [comment]
Conflicts look like they need to be resolved locally and I believe that all the CI failures are from linting (e.g., a run of `prettier` via `npm run lint:fix`)

https://github.com/apollographql/apollo-tooling/blob/c05c9e497bd613ddc8bbbc85472d1492a94ffbe7/package.json#L27

**Comment by alexanderniebuhr** [comment]
@abernix yeah you could reopen this and land it. My main concern was the VS Code Extension, so I just moved it over to the new repo.
I can solve conflicts and run prettier for you

**Review by abernix — APPROVED** [review]

**Pull request merged**
