### PR TITLE
correct implementation of ignore https verification

### LINKED ISSUE #928: ERR_INVALID_PROTOCOL when using --skipSSLValidation
I have a self-signed cert and am trying to download the schema, but I get 

› apollo service:download --skipSSLValidation --endpoint=https://localhost/graphql/
  ✔ Loading Apollo Project
  ✖ Saving schema to schema.json

    → Protocol "https:" not supported. Expected "http:"
TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"

### PR DESCRIPTION
**Pull request by septs**
TODO:

- [x] Update CHANGELOG.md\* with your change (include reference to issue & this PR)
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass

\*Make sure changelog entries note which project(s) has been affected. See older entries for examples on what this looks like.

### CODE REVIEW

**Comment by septs** [comment]
@JakeDawkins

**Comment by trevor-scheer** [comment]
Thanks so much for this PR @septs! Would you mind replicating the changes in the standard introspection provider as well?

https://github.com/apollographql/apollo-tooling/blob/1c24b14871bfa96f35c3f326a9f1022018c57468/packages/apollo-language-server/src/providers/schema/introspection.ts

**Comment by septs** [comment]
@trevor-scheer done

**Comment by trevor-scheer** [comment]
Thank you 🎉

**Comment by septs** [comment]
@trevor-scheer next release date? and closed #928 ?

**Comment by trevor-scheer** [comment]
@septs will release on Monday! ~9am PST

**Comment by trevor-scheer** [comment]
Released!
```
Successfully published:
...
 - apollo-language-server@1.14.2
 - apollo@2.17.3
```

**Comment by septs** [comment]
@trevor-scheer request update vscode-apollo

**Comment by JakeDawkins** [comment]
@septs The extension is updating right now. Should be released in a couple minutes `@1.9.2`. Let me know if there are any issues :)

**Pull request merged**
