### PR TITLE
Various fixes for Windows

### PR DESCRIPTION
**Pull request by JakeDawkins**
Fixes:
- [x] windows filepath support 
- [x] windows localSchemaFile support [spectrum discussion](https://spectrum.chat/apollo/apollo-tooling/vscode-does-not-seems-to-be-working-with-local-schema-file~7691b923-406c-4cfe-a554-77ad0b860068)
- [x] windows onHover not working
  - NOTE: it looks like it _does_ work, but only toward the end of the line. The offset it broken here somehow (maybe line endings)
- [x] windows autocomplete not working? #1167 

Summary: essentially there were 2 main issues
1. URIs weren't consistent. URI formats on windows varied between 3 or 4 different formats, and we weren't normalizing them to make sure we handled them all the same. I added a util where I saw breaks to handle them.
2. Line breaks on windows are 2 characters and we were only assuming 1 in checks inside the onHover handler, so some points on the line weren't being considered part of the token you were hovering over.

TODO:

- [x] Update CHANGELOG.md\* with your change (include reference to issue & this PR)
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [ ] Make sure all tests and linter rules pass

\*Make sure changelog entries note which project(s) has been affected. See older entries for examples on what this looks like.

### CODE REVIEW

**Comment by berrylaw** [comment]
Which one ?

**Comment by JakeDawkins** [comment]
@berrylaw still a work in progress. Right now, vscode on windows won't properly load because of an issue with matching paths. This fixes that (there's no GH issue for that one). There's also an onHover issue I need to look into before I can merge this

**Comment by dylanwulf** [comment]
Is this going to include a fix for #1167 ? Or is that something different?

**Comment by JakeDawkins** [comment]
@dylanwulf I believe these changes will fix #1167 but I can't confirm quite yet. I'm taking a look today and trying to wrap this up

**Comment by JakeDawkins** [comment]
These changes were released in Apollo VS Code 1.6.9

**Comment by dylanwulf** [comment]
@JakeDawkins Thank you! Just tried it out. The as-you-type autocomplete seems to be working correctly now, but ctrl+space is showing incorrect results. Should I make a new issue for that?

**Comment by JakeDawkins** [comment]
Great! We're getting closer 🤞 

I'll just leave #1167 open for now and add a note until I can figure out what's going on there

**Pull request merged**
