### PR TITLE
Introduced `type` keyword among the ones that need to be escaped

### PR DESCRIPTION
**Pull request by espinhogr**
TODO:

- [X] Update CHANGELOG.md\* with your change (include reference to issue & this PR)
- [X] Make sure all of the significant new logic is covered by tests
Tests are only there for the general case and not for each single keyword
- [X] Rebase your changes on master so that they can be merged easily
- [X] Make sure all tests and linter rules pass

\*Make sure changelog entries note which project(s) has been affected. See older entries for examples on what this looks like.

### CODE REVIEW

**Comment by espinhogr** [comment]
I don't know why Generated Types Check is not passing as I haven't touched the typescript generation at all.

**Comment by trevor-scheer** [comment]
@espinhogr thanks for the PR! Looks like it just needs a rebase against `master`.

**Comment by espinhogr** [comment]
@trevor-scheer  I've just rebased to the master but it seems to fail in a test on Windows, is this something known or you think it's the change I've introduced?

**Comment by trevor-scheer** [comment]
@espinhogr we've got something flaky in the tests, I re-ran and it looks good. Thanks again!

**Comment by espinhogr** [comment]
@trevor-scheer  Brilliant, happy to help!

**Pull request merged**
