### PR TITLE
Preparations for graphql@15.x.

### PR DESCRIPTION
**Pull request by abernix**
This PR makes the minimal number of changes necessary for the `apollo-tooling`'s repository's tests to pass for the planned `graphql@15.x` release.

Notable changes to implementations are as follows:

* an adjustment to account for the new `onError` callback introduced by https://github.com/graphql/graphql-js/pull/2074, which deprecated the previously used `ValidationContext.prototype.getErrors` method.

* utilize the `GraphQLEnumValueConfig` type instead of `GraphQLEnumValue` (which lead to the removal of the `name` field, which isn't actually needed when building the `values` for the `GraphQLEnumType` constructor.

Ref: https://github.com/graphql/graphql-js/issues/2303

### CODE REVIEW

**Comment by chaffeqa** [comment]
I can confirm this fixes errors in graphql v15 (which is now released).

any chance of getting this merged?

**Comment by trevor-scheer** [comment]
This PR is ready for review. For anyone following along, this is going to sit for the long weekend. However, if you'd like to try it out yourself you're welcome to install the builds from this PR directly into your project. I'll paste the links below to the builds, you can add them to your project via a typical `npm install <link to build>`

CLI build
https://105044-65563448-gh.circle-artifacts.com/0/storage/apollo/apollo-2.28.3.tgz

Language server build
https://105044-65563448-gh.circle-artifacts.com/0/storage/apollo-language-server/apollo-language-server-1.22.3.tgz

I'd love for people to try these out and let me know how they work over the next few days! Regardless, I think the next step for this PR will be to release it under the `next` tag so we can validate these changes more broadly.

**Comment by trevor-scheer** [comment]
The releases associated with this change can be found on the `next` dist-tag for the following packages

**Comment by WIStudent** [comment]
I just want to quickly point to issue https://github.com/apollographql/apollo-tooling/issues/2232 hoping that it increases the chances that the right people see it. The short version is that there are issues with the graphql peer dependency defined in @apollographql/graphql-language-service-interface and how npm@7 resolves peer dependencies.

**Pull request merged**
