### PR TITLE
Move apollo-graphql package into the apollo-tooling repo

### PR DESCRIPTION
**Pull request by trevor-scheer**
This is the first step to moving the new `apollo-graphql` package into this repo, from `apollo-server`.
The second step will be to PR the removal from `apollo-server`.

This is almost a wholesale copy/paste. A couple changes worth noting:
* Rename `dist` -> `lib` to match the pattern of this repo
* `esModuleInterop` and `target: 'es2016'` to match tsconfig of the previous project that it came from

@martijnwalraven pointed out the dependency on `node@6` within `apollo-server`, so I left that as is.

TODO:

- [x] Update CHANGELOG.md\* with your change (include reference to issue & this PR)
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by abernix** [comment]
I think this looks almost right, but the `apollo-graphql` tests aren't running.  I fixed that without too much effort (more on that in a moment) but I also thought I'd comment on the technique for the move itself and try to avoid the wholesale copy/paste which, I think, makes it more difficult to validate the gap between the two repositories (i.e. did anything go wrong?)

Since `apollo-graphql` is a relatively new repository, it was tempting to not preserve its existing Git history, but I think it's a good habit for us to save that information when possible, rather than have you take the forever-`git blame` for anything which I may have done wrong with the initial implementation of `apollo-graphql` which this imports! 😉

The steps to do so are _relatively_ straightforward with the right commands, these which assume that both repositories are using `packages/*` for their members, and might be worth showing here for posterity:

```sh
$ cp -R apollo-server apollo-server-BACKUP
$ cd apollo-server-BACKUP
$ git checkout -b just-apollo-graphql master
$ git filter-branch -f --prune-empty --subdirectory-filter packages/apollo-graphql -- --all
$ git filter-branch -f --index-filter '
    git ls-files -sz |
    perl -0pe "s{\t}{\tpackages/apollo-graphql/}" |
    GIT_INDEX_FILE=$GIT_INDEX_FILE.new \
        git update-index --clear -z --index-info &&
        mv "$GIT_INDEX_FILE.new" "$GIT_INDEX_FILE"
' HEAD
$ cd ../apollo-tooling
$ git checkout -b abernix/add-apollo-graphql
$ git remote add local ../apollo-server-BACKUP
$ git pull --allow-unrelated-histories local just-apollo-graphql --no-ff
$ # Complete the merge by solving conflicts and merging them! 🎉
```

Happy to help you grok these if it's interesting to you, but I went ahead and ran them and got things setup on a new branch in this repository: [`abernix/add-apollo-graphql`](https://github.com/apollographql/apollo-tooling/compare/abernix/add-apollo-graphql) and then rebased your changes from this PR on top of it.

The great thing about this technique is that it makes the subtle changes you needed to make very clear, as seen here: https://github.com/apollographql/apollo-tooling/commit/3decc837beef15e1b64fb61b2ccb914db044b067.

Anyhow, as the branch link above shows, I added two other commits to make testing work:

* https://github.com/apollographql/apollo-tooling/commit/bf6e3e1592200850ba3a0652675d2233a22f3416
* https://github.com/apollographql/apollo-tooling/commit/bee8eaa2b20f79c974c68ed764a50736771d4a2f

I think with those last couple commits then this PR is LGTM.

My long-winded proposition is, if this all looks good to you, would you entertain the idea of me force pushing that branch to this PR? 😸

**Comment by abernix** [comment]
Refs: https://github.com/apollographql/apollo-server/pull/2316

**Comment by abernix** [comment]
Sorry, I have no idea why I referred to the above as _relatively straightforward_.  It's obviously not.  It was relatively straightforward only because I happened to know it was possible, took very little time, and knew exactly what to look for.

**Comment by trevor-scheer** [comment]
@abernix thank you as always for the excellent information. Please force push away! We'll shoot for a merge and publish tomorrow (my morning) if you're available. Would love to discuss your technique as well (it's _super_ interesting to me!)

**Pull request merged**
